server:
  port: 9411
spring:
  application:
    name: zipkin_server
  cloud:
    inetutils:
       ignored-interfaces:
                - eth0
                - eth1
                - enp2s0f0


eureka:
  instance:
    preferIpAddress: True
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.11.223:8761/eureka/
